using System;
using System.Linq;
using FluentAssertions;
using UsurperRemake.Systems;
using UsurperRemake.UI;
using Xunit;

namespace UsurperRemake.Tests
{
    /// <summary>
    /// v0.65.7 AI NPC portrait pipeline: MiniPng decoder profile, the
    /// three-tier PortraitEncoder (determinism, footprint, SGR shape),
    /// cache-key stability, prompt construction, and settings gating.
    /// </summary>
    public class PortraitTests
    {
        // 4x4 RGBA PNG: (0,0)=red, (3,0)=green, (0,3)=blue, (3,3)=white@128a,
        // everything else opaque black. Generated by Pillow, checked into the
        // test as a stable reference for the decoder profile.
        private const string RefPngB64 =
            "iVBORw0KGgoAAAANSUhEUgAAAAQAAAAECAYAAACp8Z5+AAAAJUlEQVR4nGP8z8Dwn5EBCv4zMIDY/2F8EGBC5kAFEAr+///fCAD/4giB9lHB9wAAAABJRU5ErkJggg==";

        private static global::Character MakeNpc(
            string name = "Noric Thornbury III",
            CharacterClass cls = CharacterClass.Warrior)
        {
            return new global::Character
            {
                Name1 = name,
                Name2 = name,
                Race = CharacterRace.Gnoll,
                Sex = CharacterSex.Male,
                Class = cls,
                Age = 30,
            };
        }

        // ─── MiniPng ────────────────────────────────────────────────

        [Fact]
        public void MiniPng_DecodesReferenceImage_PixelExact()
        {
            var png = Convert.FromBase64String(RefPngB64);
            var (rgba, w, h) = MiniPng.Decode(png);

            w.Should().Be(4);
            h.Should().Be(4);
            rgba.Length.Should().Be(4 * 4 * 4);

            // (0,0) red
            rgba[0].Should().Be(255); rgba[1].Should().Be(0); rgba[2].Should().Be(0); rgba[3].Should().Be(255);
            // (3,0) green
            int o = 3 * 4;
            rgba[o].Should().Be(0); rgba[o + 1].Should().Be(255); rgba[o + 2].Should().Be(0);
            // (0,3) blue
            o = 3 * 4 * 4;
            rgba[o].Should().Be(0); rgba[o + 1].Should().Be(0); rgba[o + 2].Should().Be(255);
            // (3,3) semi-transparent white
            o = (3 * 4 + 3) * 4;
            rgba[o].Should().Be(255); rgba[o + 3].Should().Be(128);
        }

        [Fact]
        public void MiniPng_RejectsGarbage()
        {
            Action bad = () => MiniPng.Decode(new byte[] { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10 });
            bad.Should().Throw<System.IO.InvalidDataException>();

            Action truncated = () => MiniPng.Decode(
                Convert.FromBase64String(RefPngB64).Take(30).ToArray());
            truncated.Should().Throw<System.IO.InvalidDataException>();
        }

        // ─── PortraitEncoder ────────────────────────────────────────

        private static byte[] SolidRgba(int w, int h, byte r, byte g, byte b, byte a = 255)
        {
            var buf = new byte[w * h * 4];
            for (int i = 0; i < buf.Length; i += 4)
            {
                buf[i] = r; buf[i + 1] = g; buf[i + 2] = b; buf[i + 3] = a;
            }
            return buf;
        }

        [Theory]
        [InlineData(PortraitEncoder.Tier.TrueColor)]
        [InlineData(PortraitEncoder.Tier.Xterm256)]
        [InlineData(PortraitEncoder.Tier.Ansi16)]
        public void Encoder_ProducesFourteenResetTerminatedRows(PortraitEncoder.Tier tier)
        {
            var rows = PortraitEncoder.Encode(SolidRgba(128, 128, 200, 150, 120), 128, 128, tier);

            rows.Length.Should().Be(PortraitEncoder.Rows);
            foreach (var row in rows)
            {
                row.Should().EndWith("\x1b[0m", "every row must reset SGR state");
                row.Should().Contain("\x1b[", "rows are raw ANSI");
            }
        }

        [Fact]
        public void Encoder_TrueColor_EmitsExactRgbOfSolidInput()
        {
            var rows = PortraitEncoder.Encode(SolidRgba(64, 64, 10, 200, 30), 64, 64, PortraitEncoder.Tier.TrueColor);
            // Solid opaque input: every cell is (10,200,30) top and bottom.
            rows[0].Should().Contain("\x1b[38;2;10;200;30m");
            rows[0].Should().Contain("\x1b[48;2;10;200;30m");
            rows[0].Should().Contain("▀");
        }

        [Fact]
        public void Encoder_TrueColor_TransparentInputCompositesToBackdrop()
        {
            // Fully transparent image -> every pixel becomes the dark backdrop,
            // NOT black and NOT the source color.
            var rows = PortraitEncoder.Encode(SolidRgba(32, 32, 255, 255, 255, 0), 32, 32, PortraitEncoder.Tier.TrueColor);
            rows[0].Should().Contain("\x1b[38;2;12;10;18m");
            rows[0].Should().NotContain("38;2;255;255;255");
        }

        [Fact]
        public void Encoder_IsDeterministic()
        {
            var img = new byte[96 * 96 * 4];
            var rng = new Random(42);
            rng.NextBytes(img);
            for (int i = 3; i < img.Length; i += 4) img[i] = 255;

            foreach (PortraitEncoder.Tier tier in Enum.GetValues<PortraitEncoder.Tier>())
            {
                var a = PortraitEncoder.Encode(img, 96, 96, tier);
                var b = PortraitEncoder.Encode(img, 96, 96, tier);
                a.Should().BeEquivalentTo(b, o => o.WithStrictOrdering());
            }
        }

        [Fact]
        public void Encoder_Ansi16_UsesOnlyBbsSafeSgrCodes()
        {
            var img = new byte[64 * 64 * 4];
            var rng = new Random(7);
            rng.NextBytes(img);
            for (int i = 3; i < img.Length; i += 4) img[i] = 255;

            var rows = PortraitEncoder.Encode(img, 64, 64, PortraitEncoder.Tier.Ansi16);
            foreach (var row in rows)
            {
                row.Should().NotContain("38;2;", "16-color tier must not emit truecolor");
                row.Should().NotContain("38;5;", "16-color tier must not emit xterm-256");
                // Backgrounds restricted to 40-47 (bright backgrounds blink on BBS)
                foreach (var code in System.Text.RegularExpressions.Regex.Matches(row, @"\x1b\[(\d);3(\d);4(\d)m")
                             .Cast<System.Text.RegularExpressions.Match>())
                {
                    int bg = int.Parse(code.Groups[3].Value);
                    bg.Should().BeInRange(0, 7);
                }
                // Only CP437-representable glyphs
                foreach (char c in row)
                {
                    if (c == '\x1b' || (c >= ' ' && c <= '~')) continue;
                    "▀▄░▒▓█".Should().Contain(c.ToString(),
                        $"char U+{(int)c:X4} must be a CP437 block char");
                }
            }
        }

        [Fact]
        public void Encoder_RejectsBadBuffers()
        {
            Action tooSmall = () => PortraitEncoder.Encode(new byte[10], 64, 64, PortraitEncoder.Tier.TrueColor);
            tooSmall.Should().Throw<ArgumentException>();
        }

        // ─── Full pipeline: reference PNG through the encoder ───────

        [Fact]
        public void Pipeline_DecodeAndEncode_RoundTrips()
        {
            var png = Convert.FromBase64String(RefPngB64);
            var (rgba, w, h) = MiniPng.Decode(png);
            var rows = PortraitEncoder.Encode(rgba, w, h, PortraitEncoder.Tier.TrueColor);
            rows.Length.Should().Be(PortraitEncoder.Rows);
        }

        // ─── NPCPortraitSystem ──────────────────────────────────────

        [Fact]
        public void CacheKey_StableForSameIdentity_DiffersAcrossClass()
        {
            var a1 = NPCPortraitSystem.GetCacheKey(MakeNpc());
            var a2 = NPCPortraitSystem.GetCacheKey(MakeNpc());
            var b = NPCPortraitSystem.GetCacheKey(MakeNpc(cls: CharacterClass.Magician));

            a1.Should().Be(a2, "same identity must map to the same cached portrait");
            a1.Should().NotBe(b, "a class change should regenerate the portrait");
        }

        [Fact]
        public void CacheKey_IgnoresAgeAndLevel()
        {
            var young = MakeNpc();
            young.Age = 20;
            var old = MakeNpc();
            old.Age = 70;
            old.Level = 90;

            NPCPortraitSystem.GetCacheKey(young).Should().Be(NPCPortraitSystem.GetCacheKey(old),
                "aging or leveling must not churn the portrait cache");
        }

        [Fact]
        public void CachePath_IsFilesystemSafe()
        {
            var npc = MakeNpc(name: "Sir Bob \"The Rat\" O'Malley/Jr");
            string path = System.IO.Path.GetFileName(NPCPortraitSystem.GetCachePath(npc));
            path.Should().MatchRegex(@"^[a-z0-9\-]+_[0-9a-f]{10}\.png$");
        }

        [Fact]
        public void BuildPrompt_ReflectsIdentityTraits()
        {
            var npc = MakeNpc();
            string prompt = NPCPortraitSystem.BuildPrompt(npc);

            prompt.Should().Contain("gnoll", "race drives the face");
            prompt.Should().Contain("hyena-headed", "the PoC showed generic prompts drift fox-like");
            prompt.Should().Contain("warrior");
            prompt.Should().Contain("male");
            prompt.Should().Contain("Darkest Dungeon");
            prompt.Should().NotContain("crown", "commoners get no crown");

            npc.King = true;
            NPCPortraitSystem.BuildPrompt(npc).Should().Contain("crown");
        }

        [Fact]
        public void Generation_InactiveWithoutConfiguration()
        {
            // Test environment has no portrait env vars set.
            Environment.GetEnvironmentVariable("USURPER_PORTRAIT_ENABLED").Should().BeNullOrEmpty();
            NPCPortraitSystem.IsGenerationActive().Should().BeFalse(
                "generation must be opt-in via env config");
        }
    }
}
