using System.Collections.Generic;

namespace UsurperRemake.Data;

/// <summary>
/// The Tournament of Honor -- v0.62.x "Light and Dark" Phase 7 (slice 6b). A short, focused
/// three-fight ritual hosted at The Sanctum and gated on Defender+ Renown standing (Chivalry
/// >= 250). The Light-pole mirror of Anchor Road's Gauntlet, but DELIBERATELY shorter and
/// more ceremonial: where the Gauntlet is endurance against 10 waves, the Tournament is a
/// focused trial against three named foes that a Light hero would specifically be called
/// to confront -- a fallen knight (a brother betrayed), an undead lord (the desecrated dead),
/// and the Anonymous Champion (the reigning ritual winner whose name is never spoken).
///
/// Shares infrastructure with the Gauntlet:
/// - `GauntletChampionData.ArenaTier` enum + `GetTierForLevel` (tier earned by player level on full clear)
/// - `Character.ArenaChampionTier` save field (highest tier reached across either tournament)
/// - `Character.GauntletRunsToday` daily counter (so it's Tournament OR Gauntlet today, not both)
/// - `Character.PFights` per-day combat-slot counter
///
/// Phase 7 first-slice scope deliberately constrained: 3 champions, no warmup waves, English
/// fields drive the source-of-truth with `tournament.champ.{id}.*` loc keys overriding for
/// localized sessions. Slice 7b can add additional champions, the cosmetic title-flavor split
/// (Honorbound vs Hopeful at lower tiers), and the warmup-wave structure if the loop proves
/// to want more length.
/// </summary>
public static class HonorTournamentData
{
    public enum HonorChampionRole
    {
        /// <summary>Fallen knight -- mirror of a Paladin who lost their faith. Heavy melee, paladin gear, broken combat style.</summary>
        FallenPaladin,
        /// <summary>Undead lord -- dark magic, bone-summons, drain. The desecrated dead.</summary>
        UndeadLord,
        /// <summary>The Anonymous Champion -- the reigning ritual winner. Multi-phase, balanced threat. Never speaks.</summary>
        AnonymousChampion
    }

    public class HonorChampion
    {
        public string Id { get; init; } = "";
        public string Name { get; init; } = "";
        public string Title { get; init; } = "";
        public HonorChampionRole Role { get; init; }

        /// <summary>HP multiplier on base scaled stats. Modest -- Tournament fights are shorter than Gauntlet so
        /// HP can be higher per-fight without making the whole loop tedious.</summary>
        public float HpMultiplier { get; init; }
        public float AttackMultiplier { get; init; }
        public float DefenseMultiplier { get; init; }

        /// <summary>Player-level offset for this champion. Tournament champions scale +3/+5/+7 across the three
        /// slots (vs Gauntlet's +2..+14 spread) -- the gap is tighter because there are fewer fights.</summary>
        public int LevelBonus { get; init; }

        /// <summary>The herald's announcement before combat. 2-3 lines. May reference {0} for the player's display name.</summary>
        public string[] EntranceAnnouncement { get; init; } = System.Array.Empty<string>();

        /// <summary>One-line lore reveal printed in italics after the entrance.</summary>
        public string LoreLine { get; init; } = "";

        /// <summary>What the crowd / hall does when this champion walks out.</summary>
        public string CrowdReaction { get; init; } = "";

        /// <summary>Themed equipment drop on defeat -- runtime stats are generated by the tournament
        /// method using LootGenerator scaled to player level.</summary>
        public ChampionDrop Drop { get; init; } = new();

        /// <summary>Monster abilities the champion uses. Picked at random per round by the existing
        /// MonsterAbilities pipeline. Names must match valid AbilityType enum entries.</summary>
        public string[] SpecialAbilities { get; init; } = System.Array.Empty<string>();

        // Localized accessors. English fields are the source/fallback; localized keys override.
        private static string LocOr(string key, string fallback)
        {
            var v = UsurperRemake.Systems.Loc.Get(key);
            return v == key ? fallback : v;
        }
        public string[] LocEntrance()
        {
            var r = new string[EntranceAnnouncement.Length];
            for (int i = 0; i < r.Length; i++)
                r[i] = LocOr($"tournament.champ.{Id}.entrance.{i}", EntranceAnnouncement[i]);
            return r;
        }
        public string LocLore() => LocOr($"tournament.champ.{Id}.lore", LoreLine);
        public string LocCrowd() => LocOr($"tournament.champ.{Id}.crowd", CrowdReaction);
        public string LocDropFlavor() => LocOr($"tournament.champ.{Id}.drop_flavor", Drop.FlavorDescription);
        public string LocName() => LocOr($"tournament.champ.{Id}.name", Name);
    }

    public class ChampionDrop
    {
        public string ItemName { get; init; } = "";
        public string SlotHint { get; init; } = "";
        public string FlavorDescription { get; init; } = "";
    }

    public static readonly HonorChampion[] Champions = new[]
    {
        // ========================================================================
        // WAVE 1 -- Sir Aedric the Lapsed. Once a paladin of Aurelion. After his
        // sister was lost to Noctura, he turned away from the light and now serves
        // only the bottle and the blade. Narratively echoes Aurelion's tragedy.
        // ========================================================================
        new HonorChampion
        {
            Id = "aedric_lapsed",
            Name = "Sir Aedric the Lapsed",
            Title = "Once-Knight of the Lantern",
            Role = HonorChampionRole.FallenPaladin,
            HpMultiplier = 1.6f,
            AttackMultiplier = 1.3f,
            DefenseMultiplier = 1.1f,
            LevelBonus = 3,
            EntranceAnnouncement = new[]
            {
                "The herald reads from a scroll, voice carefully neutral.",
                "\"From the broken cloister of Aurelion -- Sir Aedric the Lapsed. He has",
                " forsaken his oath. He fights to remember what it cost him.\""
            },
            LoreLine = "His armor still bears the lantern-mark, but the lantern has been scratched out.",
            CrowdReaction = "The hall falls silent. A few in the upper galleries look away.",
            Drop = new ChampionDrop
            {
                ItemName = "Aedric's Tarnished Blade",
                SlotHint = "MainHand",
                FlavorDescription = "A longsword whose holy edge has dulled. Still keen enough to grieve with."
            },
            SpecialAbilities = new[] { "CriticalStrike", "Cleave", "Regeneration" }
        },

        // ========================================================================
        // WAVE 2 -- Marrowking Vex. An undead lord raised through forbidden rite.
        // Pulls bone-magic from the dust of every gladiator who ever died here.
        // Holy Smite (the Light-pole alignment passive from Slice 1) hits him at
        // its full +10% damage, so high-Chivalry players have a meaningful edge.
        // ========================================================================
        new HonorChampion
        {
            Id = "marrowking_vex",
            Name = "Marrowking Vex",
            Title = "Lord of the Quiet Dust",
            Role = HonorChampionRole.UndeadLord,
            HpMultiplier = 2.0f,
            AttackMultiplier = 1.2f,
            DefenseMultiplier = 1.3f,
            LevelBonus = 5,
            EntranceAnnouncement = new[]
            {
                "Smoke curls from the floor. The hall lights guttering low.",
                "\"From the sealed crypt beneath the city -- the Marrowking, Vex of the",
                " Quiet Dust. The ground itself remembers him. Cleanse the ground.\""
            },
            LoreLine = "He was a magistrate once. He sentenced a hundred to die. They came back with him.",
            CrowdReaction = "Patrons in the front rows draw small wards on their wrists.",
            Drop = new ChampionDrop
            {
                ItemName = "Marrowking's Sigil",
                SlotHint = "Neck",
                FlavorDescription = "A blackened pendant marked with the sigil of the Quiet Dust. Wearers say it whispers."
            },
            // Phylactery (self-heal when low HP) is the headline survivability ability. Curse +
            // LifeDrain both work and lean into the "undead lord drains the living" fantasy
            // without depending on the SummonMonsters flag that CombatEngine never consumes
            // (pre-existing engine dead code; flagged by combat-reviewer but out of scope here).
            SpecialAbilities = new[] { "LifeDrain", "Curse", "Phylactery" }
        },

        // ========================================================================
        // WAVE 3 -- The Anonymous Champion. Never speaks. Wears no colors. The
        // reigning winner of the Tournament since memory. Some say there have been
        // many; some say one and the same. Multi-phase final-fight encounter.
        // ========================================================================
        new HonorChampion
        {
            Id = "anonymous_champion",
            Name = "The Anonymous Champion",
            Title = "Unnamed, Unbeaten",
            Role = HonorChampionRole.AnonymousChampion,
            HpMultiplier = 2.5f,
            AttackMultiplier = 1.5f,
            DefenseMultiplier = 1.4f,
            LevelBonus = 7,
            EntranceAnnouncement = new[]
            {
                "No herald speaks. The hall darkens to a single point of light.",
                "A figure walks out. Plain steel. Plain mask. No colors at all.",
                "They bow. They draw. The tournament expects no introduction it does not give itself."
            },
            LoreLine = "They have stood in this hall longer than any record. They have always won.",
            CrowdReaction = "The hall is utterly silent. Even the vendors stop calling.",
            Drop = new ChampionDrop
            {
                ItemName = "The Anonymous Mask",
                SlotHint = "Face",
                FlavorDescription = "A plain steel mask, perfectly fitted. It hums faintly when held."
            },
            SpecialAbilities = new[] { "CriticalStrike", "Multiattack", "Vanish" }
        }
    };

    /// <summary>
    /// Reward tuning for a full Tournament clear. Multiplies by player level on victory.
    /// Tighter spread than Gauntlet's (which goes 200..1500 gold/level across 5 tiers)
    /// because the Tournament is a shorter ritual -- gold per minute is comparable but the
    /// per-clear payout sits in the upper-mid range. Fame bonus matches Gauntlet's so a
    /// full clear contributes equally to knighthood eligibility.
    ///
    /// Chivalry is awarded PER WAVE (10/15/20 across the three waves) inside the tournament
    /// loop via AlignmentSystem.ChangeAlignment, so the v0.60.0 DR curve fires and a Hero+
    /// player still gets a meaningful but modest climb. NOT applied here in the per-tier
    /// summary because tier-clears already trigger a tier-up message.
    /// </summary>
    public class TierRewards
    {
        public int GoldMultiplierPerLevel { get; init; }
        public int XpMultiplierPerLevel { get; init; }
        public int FameBonus { get; init; }
    }

    public static TierRewards GetTierRewards(GauntletChampionData.ArenaTier tier) => tier switch
    {
        GauntletChampionData.ArenaTier.Hopeful       => new TierRewards { GoldMultiplierPerLevel =  250, XpMultiplierPerLevel = 130, FameBonus =  35 },
        GauntletChampionData.ArenaTier.Veteran       => new TierRewards { GoldMultiplierPerLevel =  500, XpMultiplierPerLevel = 250, FameBonus =  60 },
        GauntletChampionData.ArenaTier.Master        => new TierRewards { GoldMultiplierPerLevel =  850, XpMultiplierPerLevel = 420, FameBonus =  90 },
        GauntletChampionData.ArenaTier.Champion      => new TierRewards { GoldMultiplierPerLevel = 1300, XpMultiplierPerLevel = 600, FameBonus = 120 },
        GauntletChampionData.ArenaTier.GrandChampion => new TierRewards { GoldMultiplierPerLevel = 1700, XpMultiplierPerLevel = 820, FameBonus = 175 },
        _ => new TierRewards()
    };
}
